#theme: minima
remote_theme: jekyll/minima

# Site settings
title: Oh~ 赛赛
email: rmself@qq.com
description:

baseurl: ""
url: "https://ohsaisai.com"

excerpt_separator: <!--more-->
show_excerpts: true
paginate: 10
paginate_path: "/page:num/"

lang: zh-cmn-Hans

plugins:
- jekyll-remote-theme
- jekyll-paginate
